### PR TITLE
files added and ready for review

### PR DESCRIPTION
**Pull request by aneallaryea100**

### CODE REVIEW

**Review by gtekle — CHANGES_REQUESTED** [review]
Hi @aneallaryea100 :wave:, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has no pull request summary and no descriptive PR title. You should also update your ReadMe file according to the Microverse [template](https://github.com/microverseinc/readme-template/blob/master/README.md).
image


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by aneallaryea100** [comment]
My code is ready for review. I added the work and about section to my project.

**Comment by aneallaryea100** [comment]
my code is ready for review.

**Comment by Kakalanp** [comment]
# Hello there @aneallaryea100  hi

While you made a great effort in this project, unfortunately, I cannot proceed to review your code. :cry: 

## Invalid Code Review Request :no_entry: 

You have submitted a project, that has no descriptive Pull request description or title, as explained by the last reviewer, try to add a description of what additions you have made here :nerd_face: 
image


almost there

Your Code Review Request will be marked as invalid in your Dashboard, which means **you won't lose a review request**, please submit a new one once you are ready 🙏

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

### _Invalid Code Review Request **does not count** into the code reviews limit._ :mag:

**Comment by aneallaryea100** [comment]
adding the full skeleton of the portofilo project

**Pull request closed without merging**
